export const NounJSON = [
    {
      "type": "pastry",
       "content": [
            "waffle",
            "fritter",
            "pie",
            "tart",
            "donut",
            "cake",
            "brownie",
            "custard",
            "pudding",
            "muffin",
            "lollipop",
            "biscuit",
            "cookie"
        ],  
    },
    {
       "type": "body-part",
       "content": [
            "head",
            "dick",
            "foot",
            "feet",
            "fingers",
            "toes",
            "nipples",
            "crotch",
            "neck",
            "taint",
            "knees",
            "joints",
            "spine",
            "eye-balls",
            "eye-sockets",
            "mouth",
            "throat",
            "nose",
            "sinuses",
            "intestines",
            "heart",
            "colon",
            "ass",
            "cunt",
            "boner",
            "boner-shrinker",
            "meat curtains",
            "jiz",
            "balls",
            "nut-sack",
            "shaft",
            "clit",
            "butt-nugget",
            "micro-penis"
        ], 
    },
    {
        "type": "personality",
        "content": [
            "idiot",
            "maniac",
            "lunatic",
            "slut",
            "hooker",
            "failure",
            "clown",
            "good for nothing",
            "slob",
            "creep",
            "weirdo",
            "racist",
            "hag",
            "pig",
            "fascist",
            "monster",
            "boot-licker",
            "ass-kisser",
            "freak",
            "fucktard",
            "has-been",
            "bitch",
            "douche-bag"
        ],
    },    
    {
        "type": "profession",
        "content": [
            "whore",
            "politician",
            "lawyer",
            "chantoosie",
            "milk man",
            "spinster",
            "hag",
            "witch",
            "priest"
        ],
    },    
    {
        "type": "animal",
        "content": [
            "pony",
            "pig",
            "hog",
            "snake",
            "spider",
            "hyenna",
            "toad",
            "worm",
            "weasle",
            "rat",
            "cockroach",
            "leach",
            "wallaby",
            "goblin",
            "troll",
            "banshee",
            "orc",
            "werewolf"
        ],
    },    
    {
        "type": "other",
        "content": [
            "ass-wipe"
        ]
    }    
        
]
    
